#!/bin/bash

SYSCONFIG=/etc/sysconfig/traefik

sysconfig_traefik_check() {

	if [ -f $SYSCONFIG ] ; then
		source $SYSCONFIG
	else
		echo $SYSCONFIG does not exist. This is no good.
		exit 1
	fi

}

etcd_api_check() {

	if [ $ETCD_USEAPIV3 == "true" ] ; then
		ETCDCTL_API=3
		export ETCDCTL_API
	else
		echo etcd API v2 not supported, lulz.
		exit 1
	fi
		
}

sysconfig_traefik_check
etcd_api_check

